.define T_TILESET 1
.define T_BGF T_TILESET+0
.define T_BGSA T_TILESET+1
.define T_GND T_TILESET+2
.define T_GNDB T_TILESET+3
.define T_COR_UL T_TILESET+4
.define T_COR_U T_TILESET+5
.define T_COR_UR T_TILESET+6
.define T_COR_DL T_TILESET+7
.define T_COR_D T_TILESET+8
.define T_COR_DR T_TILESET+9
.define T_COL_A T_TILESET+10
.define T_COL_B T_TILESET+11
.define T_COL_C T_TILESET+12
.define T_DIRT_A T_TILESET+13
.define T_DIRT_B T_TILESET+14
.define T_BGSB T_TILESET+15

.define T_CLOUDA 18
.define T_CLOUDB T_CLOUDA+10
.define T_CLOUDC T_CLOUDB+12

.define T_OBJECTS 52
.define T_OBJECTSR T_OBJECTS+2

.define T_BLACK 76

.define T_FONT 78

.define T_PLAYER 94


.define T_FONTGO 200
