; Tile index $000
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $001
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FE $FF $03 $03 $FC $FF
; Tile index $002
.db $00 $00 $FF $FF $00 $00 $FF $FF $01 $01 $FE $FF $0F $0F $F0 $FF $3F $3F $C0 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $003
.db $03 $03 $FC $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FB $03 $FC
; Tile index $004
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $F7 $07 $F8 $FF $BF $3F $C0 $FF $FF $7F $80
; Tile index $005
.db $C0 $C0 $3F $FF $FE $FE $01 $FF $FF $F3 $02 $FD $FF $DF $1F $E0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $006
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $01 $FD $FE $0F $07 $F7 $F8
; Tile index $007
.db $07 $07 $F8 $FF $0F $0F $F0 $FF $1F $1F $E0 $FF $3F $3F $C0 $FF $7F $7F $80 $FF $7F $B7 $30 $CF $FF $FD $FC $03 $FF $FF $FE $01
; Tile index $008
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $CF $0C $F3 $FF $FF $7E $81 $FF $FE $7E $81 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80
; Tile index $009
.db $FF $FF $1F $E0 $FF $DF $1F $E0 $FF $FF $3F $C0 $FF $BF $3F $C0 $FF $FF $7F $80 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $00A
.db $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FD $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FD $7D $82
; Tile index $00B
.db $FF $FD $FC $03 $FF $EF $E0 $1F $FF $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F7 $07 $F8 $FF $BF $3F $C0 $FF $FF $FF $00
; Tile index $00C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $00D
.db $E0 $E0 $1F $FF $F0 $F0 $0F $FF $F8 $F8 $07 $FF $FC $FC $03 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $00E
.db $00 $00 $FF $FF $00 $00 $FF $FF $01 $00 $FE $FF $03 $03 $FF $FC $0F $07 $F7 $F8 $1F $0F $EF $F0 $1F $1F $FF $E0 $3F $3F $FF $C0
; Tile index $00F
.db $00 $00 $FF $FF $00 $00 $FF $FF $F8 $70 $77 $8F $FE $FC $FD $03 $FE $FE $FF $01 $FF $FE $FE $01 $FF $FF $FF $00 $DF $8F $AF $70
; Tile index $010
.db $1F $1F $FF $E0 $3F $1F $DF $E0 $3F $3F $FF $C0 $7F $3F $BF $C0 $7F $3F $BE $C1 $7F $7D $FC $83 $7F $7F $FC $83 $7F $7F $FC $83
; Tile index $011
.db $FF $FE $FE $01 $FF $FE $FE $01 $FF $FF $FF $00 $FF $3F $3F $C0 $FF $DF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $DF $1F $E0
; Tile index $012
.db $FF $FF $7F $80 $FF $FD $7D $82 $FF $FE $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83
; Tile index $013
.db $FF $FF $FF $00 $FF $DF $DF $20 $FF $FF $DF $20 $FF $BF $9F $60 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0
; Tile index $014
.db $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FD $7C $83 $FF $FF $7C $83 $FF $FF $7C $83
; Tile index $015
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FD $FC $03 $FF $E7 $E0 $1F $FF $7F $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F7 $07 $F8
; Tile index $016
.db $C0 $C0 $3F $FF $E0 $E0 $1F $FF $F0 $F0 $0F $FF $F0 $F0 $0F $FF $F8 $F8 $07 $FF $F8 $F8 $07 $FF $F8 $F8 $07 $FF $FC $FC $03 $FF
; Tile index $017
.db $7F $3E $BE $C1 $7E $3C $BD $C3 $7C $7C $FF $83 $FC $78 $7B $87 $F8 $78 $7F $87 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07
; Tile index $018
.db $0F $0F $FF $F0 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $03 $01 $FD $FE $1F $0F $EF $F0
; Tile index $019
.db $7F $7F $FC $83 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $FF $FD $7C $83 $FF $FF $7C $83
; Tile index $01A
.db $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $3F $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0
; Tile index $01B
.db $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83
; Tile index $01C
.db $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0
; Tile index $01D
.db $FF $FF $7C $83 $FF $FD $7D $82 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $7F $80 $FF $F9 $78 $87
; Tile index $01E
.db $FF $BF $3F $C0 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $F9 $F8 $07 $FF $EF $E0 $1F $FF $3F $00 $FF $FF $FF $00 $FF
; Tile index $01F
.db $FC $FC $03 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $020
.db $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07 $F8 $F8 $FF $07
; Tile index $021
.db $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $6F $EF $90 $0F $0F $FF $F0 $0F $0F $FF $F0 $1F $1F $FF $E0 $3F $1E $DE $E1
; Tile index $022
.db $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0 $FF $FD $1C $E3 $FF $FF $00 $FF
; Tile index $023
.db $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $FF $7C $83 $FF $F7 $70 $8F $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $024
.db $FF $FF $1F $E0 $FF $FB $18 $E7 $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $025
.db $FF $CF $40 $BF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $026
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E7 $06 $F9
; Tile index $027
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $0F $07 $F7 $F8 $7F $3F $BF $C0 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $028
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $FC $78 $7B $87 $FE $FE $FF $01 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $029
.db $FC $78 $7B $87 $FF $7C $7C $83 $7F $7F $FF $80 $7F $3F $BF $C0 $3F $3F $FF $C0 $1F $0F $EF $F0 $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $02A
.db $7E $7E $FF $81 $FE $FE $FF $01 $FE $FC $FD $03 $FC $F8 $FB $07 $F0 $F0 $FF $0F $E0 $80 $9F $7F $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $02B
.db $FF $FF $7C $83 $FF $E7 $60 $9F $7F $7F $80 $FF $7F $7F $80 $FF $7F $7F $80 $FF $7F $7F $80 $FF $7F $7F $80 $FF $3F $3F $C0 $FF
; Tile index $02C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E7 $00 $FF
; Tile index $02D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F7 $06 $F9 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1
; Tile index $02E
.db $FF $FF $00 $FF $FF $FD $01 $FE $FF $EF $0F $F0 $FF $7F $7F $80 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $01
; Tile index $02F
.db $FF $BF $3E $C1 $FF $FF $FE $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FA $F9 $07 $FE $DE $C1 $3F $FC $FC $03 $FF
; Tile index $030
.db $FF $FF $FF $00 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FF $FD $FD $02
; Tile index $031
.db $BF $1F $5F $E0 $1F $0F $EF $F0 $0F $0F $FF $F0 $0F $0F $FF $F0 $1F $0F $EF $F0 $1F $1F $FF $E0 $7F $3E $BE $C1 $FE $FE $FF $01
; Tile index $032
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FE $00 $FF $FF $F7 $07 $F8 $FF $EF $0F $F0 $FF $FF $3F $C0 $FF $BF $3F $C0
; Tile index $033
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $6F $60 $9F $FF $FB $F8 $07 $FF $FF $FC $03 $FF $FD $FC $03 $FF $FD $FC $03
; Tile index $034
.db $FF $7F $78 $87 $FF $FF $F8 $07 $FF $FB $F8 $07 $FF $FF $FC $03 $FF $7F $7C $83 $FF $7F $7C $83 $FF $FF $7C $83 $FF $FD $7C $83
; Tile index $035
.db $FF $FF $3E $C1 $FF $BF $3E $C1 $FF $BF $3E $C1 $FF $FD $7C $83 $FF $FD $7C $83 $FF $FF $7C $83 $FF $7F $7C $83 $FF $7F $7C $83
; Tile index $036
.db $FF $FB $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FB $FB $04 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $037
.db $FC $FC $03 $FF $F8 $F8 $07 $FF $FE $EE $0F $F1 $FE $7E $7F $81 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FC $F8 $FB $07
; Tile index $038
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FE $FC $FD $03 $FC $FC $FF $03
; Tile index $039
.db $FE $FC $FD $03 $FE $FE $FF $01 $FF $FE $FE $01 $FF $FF $FF $00 $FF $FF $FF $00 $FF $3F $3F $C0 $3F $1F $DF $E0 $1F $1F $FF $E0
; Tile index $03A
.db $FF $FF $7F $80 $FF $7E $7E $81 $FF $7F $7C $83 $FF $FB $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07
; Tile index $03B
.db $FF $FF $FE $01 $FF $7F $7E $81 $FF $BF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1
; Tile index $03C
.db $FF $FF $7E $81 $FF $BF $3E $C1 $FF $FF $3E $C1 $FF $FE $3E $C1 $FF $DF $1F $E0 $FF $DF $1F $E0 $FF $FF $1F $E0 $FF $FF $1F $E0
; Tile index $03D
.db $FF $FB $F8 $07 $FF $FB $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $FF $F0 $0F
; Tile index $03E
.db $FF $FF $FF $00 $FF $FE $FE $01 $FF $FB $F8 $07 $FE $FE $F9 $07 $FC $FC $FB $07 $F8 $F8 $FF $07 $FF $FB $FB $04 $FF $FF $FF $00
; Tile index $03F
.db $F0 $C0 $CF $3F $80 $80 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $1E $0E $EF $F1 $FE $7E $7F $81 $FE $FE $FF $01 $FE $FE $FF $01
; Tile index $040
.db $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $FC $FC $FF $03 $F0 $E0 $EF $1F
; Tile index $041
.db $1F $1F $FF $E0 $1F $1F $FF $E0 $1F $1F $FF $E0 $1F $1F $FF $E0 $1E $1C $FD $E3 $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $042
.db $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FF $F8 $07 $FF $FB $F8 $07 $FF $FF $FC $03
; Tile index $043
.db $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $FF $3E $C1 $FF $BF $3E $C1 $FF $FF $7E $81 $FF $7F $7E $81
; Tile index $044
.db $FF $EF $0F $F0 $FF $EF $0F $F0 $FF $FF $0F $F0 $FF $FF $0F $F0 $FF $F7 $07 $F8 $FF $FF $07 $F8 $FF $FF $07 $F8 $C7 $C3 $3B $FC
; Tile index $045
.db $FF $FF $F0 $0F $FF $FF $F0 $0F $FE $EE $E1 $1F $FC $FC $E3 $1F $F0 $F0 $EF $1F $E0 $E0 $FF $1F $E0 $C0 $DF $3F $C0 $C0 $FF $3F
; Tile index $046
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FE $FE $01 $FC $F0 $F3 $0F $E0 $80 $9F $7F $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $047
.db $FE $FE $FF $01 $FC $F0 $F3 $0F $E0 $C0 $DF $3F $80 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $048
.db $FF $7F $7F $80 $FF $7F $7F $80 $7F $7F $FF $80 $7F $3F $BF $C0 $3F $3F $FF $C0 $1F $0F $EF $F0 $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $049
.db $FE $FC $FD $03 $FE $FC $FD $03 $FC $FC $FF $03 $F8 $F8 $FF $07 $F0 $E0 $EF $1F $C0 $80 $BF $7F $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $04A
.db $03 $02 $FE $FD $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $04B
.db $80 $00 $7F $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF
; Tile index $04C
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $77 $CA $BD $42 $63 $DE $BD $7C $7E $FD $83 $40 $60 $DF $BF $40 $60 $DF $BF $40 $60 $DF $BF
; Tile index $04D
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $77 $CA $BD $42 $63 $DE $BD $7C $7E $FD $83 $44 $6E $D5 $BB $42 $66 $DB $BD $41 $63 $DD $BE
; Tile index $04E
.db $00 $00 $FF $FF $3F $7F $BF $C0 $40 $70 $CF $BF $40 $60 $DF $BF $78 $7C $FB $87 $40 $60 $DF $BF $40 $60 $DF $BF $3F $7F $BF $C0
; Tile index $04F
.db $00 $00 $FF $FF $3E $7F $BE $C1 $41 $63 $DD $BE $40 $60 $DF $BF $3E $7F $BE $C1 $01 $03 $FD $FE $41 $63 $DD $BE $3E $7F $BE $C1
; Tile index $050
.db $00 $00 $FF $FF $7C $7E $FD $83 $42 $67 $DA $BD $42 $63 $DE $BD $7C $7E $FD $83 $42 $63 $DE $BD $42 $67 $DA $BD $7C $7E $FD $83
; Tile index $051
.db $00 $00 $FF $FF $42 $43 $FE $BD $42 $43 $FE $BD $42 $43 $FE $BD $42 $43 $FE $BD $42 $43 $FE $BD $42 $67 $DA $BD $3C $7E $BD $C3
; Tile index $052
.db $00 $00 $FF $FF $3E $7F $BE $C1 $08 $1C $EB $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7
; Tile index $053
.db $00 $00 $FF $FF $1C $3E $DD $E3 $22 $77 $AA $DD $41 $63 $DD $BE $41 $61 $DF $BE $41 $63 $DD $BE $22 $77 $AA $DD $1C $3E $DD $E3
; Tile index $054
.db $00 $00 $FF $FF $41 $61 $DF $BE $61 $71 $EF $9E $51 $79 $D7 $AE $49 $49 $FF $B6 $45 $4F $F5 $BA $43 $47 $FB $BC $41 $43 $FD $BE
; Tile index $055
.db $00 $00 $FF $FF $08 $18 $EF $F7 $18 $38 $DF $E7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $18 $EF $F7 $1C $3E $DD $E3
; Tile index $056
.db $00 $00 $FF $FF $41 $41 $FF $BE $41 $63 $DD $BE $22 $63 $BE $DD $1C $3E $DD $E3 $08 $1C $EB $F7 $08 $08 $FF $F7 $08 $08 $FF $F7
; Tile index $057
.db $00 $00 $FF $FF $08 $1C $EB $F7 $14 $14 $FF $EB $14 $36 $DD $EB $3E $3E $FF $C1 $22 $63 $BE $DD $41 $63 $DD $BE $41 $41 $FF $BE
; Tile index $058
.db $00 $00 $FF $FF $3E $7F $BE $C1 $41 $63 $DD $BE $40 $40 $FF $BF $47 $47 $FF $B8 $41 $43 $FD $BE $41 $63 $DD $BE $3E $7F $BE $C1
; Tile index $059
.db $00 $00 $FF $FF $1C $1C $FF $E3 $08 $1C $EB $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $1C $EB $F7 $1C $1C $FF $E3
