; Tile index $000
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $66 $DB $BD $42 $42 $FF $BD $42 $42 $FF $BD $42 $42 $FF $BD $42 $66 $DB $BD $3C $7E $BD $C3
; Tile index $001
.db $00 $00 $FF $FF $08 $18 $EF $F7 $18 $38 $DF $E7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $08 $FF $F7 $08 $18 $EF $F7 $1C $3E $DD $E3
; Tile index $002
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $66 $DB $BD $02 $06 $FB $FD $04 $0E $F5 $FB $18 $38 $DF $E7 $20 $30 $EF $DF $7E $7E $FF $81
; Tile index $003
.db $00 $00 $FF $FF $7E $7E $FF $81 $04 $0E $F5 $FB $08 $0C $FB $F7 $1C $1E $FD $E3 $02 $06 $FB $FD $42 $66 $DB $BD $3C $7E $BD $C3
; Tile index $004
.db $00 $00 $FF $FF $20 $20 $FF $DF $20 $62 $BD $DF $42 $66 $DB $BD $7E $7E $FF $81 $02 $06 $FB $FD $02 $02 $FF $FD $02 $02 $FF $FD
; Tile index $005
.db $00 $00 $FF $FF $7E $7E $FF $81 $40 $60 $DF $BF $7C $7E $FD $83 $42 $66 $DB $BD $02 $02 $FF $FD $42 $66 $DB $BD $3C $7E $BD $C3
; Tile index $006
.db $00 $00 $FF $FF $18 $3C $DB $E7 $20 $60 $BF $DF $40 $60 $DF $BF $7C $7E $FD $83 $42 $46 $FB $BD $42 $66 $DB $BD $3C $7E $BD $C3
; Tile index $007
.db $00 $00 $FF $FF $7E $7E $FF $81 $02 $06 $FB $FD $04 $06 $FD $FB $04 $0C $F7 $FB $08 $0C $FB $F7 $08 $08 $FF $F7 $08 $08 $FF $F7
; Tile index $008
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $42 $FF $BD $42 $66 $DB $BD $3C $7E $BD $C3 $42 $42 $FF $BD $42 $66 $DB $BD $3C $7E $BD $C3
; Tile index $009
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $66 $DB $BD $42 $62 $DF $BD $3E $7E $BF $C1 $02 $06 $FB $FD $04 $06 $FD $FB $18 $3C $DB $E7
; Tile index $00A
.db $00 $00 $FF $FF $3E $7F $BE $C1 $41 $63 $DD $BE $40 $60 $DF $BF $3E $7F $BE $C1 $01 $03 $FD $FE $41 $63 $DD $BE $3E $7F $BE $C1
; Tile index $00B
.db $00 $00 $FF $FF $1C $3E $DD $E3 $22 $77 $AA $DD $40 $60 $DF $BF $40 $60 $DF $BF $40 $60 $DF $BF $22 $77 $AA $DD $1C $3E $DD $E3
; Tile index $00C
.db $00 $00 $FF $FF $1C $3E $DD $E3 $22 $77 $AA $DD $41 $63 $DD $BE $41 $61 $DF $BE $41 $63 $DD $BE $22 $77 $AA $DD $1C $3E $DD $E3
; Tile index $00D
.db $00 $00 $FF $FF $3C $7E $BD $C3 $42 $77 $CA $BD $42 $63 $DE $BD $7C $7E $FD $83 $44 $6E $D5 $BB $42 $66 $DB $BD $41 $63 $DD $BE
; Tile index $00E
.db $00 $00 $FF $FF $3F $7F $BF $C0 $40 $70 $CF $BF $40 $60 $DF $BF $78 $7C $FB $87 $40 $60 $DF $BF $40 $60 $DF $BF $3F $7F $BF $C0
; Tile index $00F
.db $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $20 $30 $EF $DF $00 $30 $CF $FF $00 $00 $FF $FF $20 $30 $EF $DF $00 $30 $CF $FF
